# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1719b946127f1b431774a742121236f56d0ce79e666193bab3012562495b022679b648f5f63d25c11f341b054e57782d8938eb51b385a7dc9199cc5947c6c24

test:
  secret_key_base: 31c08a61b1508a8e236cce4d38ae9f8ab10d95f2c4f4079841cf082209481877e05f5ce42c46897a27f3d4f31498fff28ddabaac05bdd86b3adf007507062b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
